namespace QuanLyDiemSV.GUI.User_Control
{
    partial class UC_HocPhan
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UC_HocPhan));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            this.dtgvHocPhan = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label8 = new System.Windows.Forms.Label();
            this.cbEditKhoa = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txbHinhThucThi = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txbMaHP = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txbTenHP = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbSoTiet = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txbSoTinChi = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnSua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.cbFindKhoa = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txbFindHP = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.btnXem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFind = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvHocPhan)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // dtgvHocPhan
            // 
            this.dtgvHocPhan.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtgvHocPhan.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgvHocPhan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgvHocPhan.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgvHocPhan.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgvHocPhan.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgvHocPhan.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgvHocPhan.ColumnHeadersHeight = 40;
            this.dtgvHocPhan.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtgvHocPhan.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvHocPhan.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvHocPhan.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvHocPhan.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgvHocPhan.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtgvHocPhan.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvHocPhan.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtgvHocPhan.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgvHocPhan.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgvHocPhan.CurrentTheme.Name = null;
            this.dtgvHocPhan.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgvHocPhan.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvHocPhan.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvHocPhan.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvHocPhan.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgvHocPhan.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgvHocPhan.EnableHeadersVisualStyles = false;
            this.dtgvHocPhan.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvHocPhan.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtgvHocPhan.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgvHocPhan.HeaderForeColor = System.Drawing.Color.White;
            this.dtgvHocPhan.Location = new System.Drawing.Point(24, 137);
            this.dtgvHocPhan.Name = "dtgvHocPhan";
            this.dtgvHocPhan.RowHeadersVisible = false;
            this.dtgvHocPhan.RowHeadersWidth = 51;
            this.dtgvHocPhan.RowTemplate.Height = 40;
            this.dtgvHocPhan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgvHocPhan.Size = new System.Drawing.Size(504, 442);
            this.dtgvHocPhan.TabIndex = 1;
            this.dtgvHocPhan.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btnXem);
            this.groupBox1.Controls.Add(this.label8);
            this.groupBox1.Controls.Add(this.cbEditKhoa);
            this.groupBox1.Controls.Add(this.txbHinhThucThi);
            this.groupBox1.Controls.Add(this.txbMaHP);
            this.groupBox1.Controls.Add(this.txbTenHP);
            this.groupBox1.Controls.Add(this.btnXoa);
            this.groupBox1.Controls.Add(this.txbSoTiet);
            this.groupBox1.Controls.Add(this.txbSoTinChi);
            this.groupBox1.Controls.Add(this.btnSua);
            this.groupBox1.Controls.Add(this.btnThem);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.groupBox1.Location = new System.Drawing.Point(548, 137);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(437, 442);
            this.groupBox1.TabIndex = 18;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Chỉnh sửa";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label8.Location = new System.Drawing.Point(21, 341);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(62, 27);
            this.label8.TabIndex = 19;
            this.label8.Text = "Khoa";
            // 
            // cbEditKhoa
            // 
            this.cbEditKhoa.BackColor = System.Drawing.Color.White;
            this.cbEditKhoa.BorderRadius = 0;
            this.cbEditKhoa.Color = System.Drawing.Color.SeaGreen;
            this.cbEditKhoa.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbEditKhoa.DisabledColor = System.Drawing.Color.Gray;
            this.cbEditKhoa.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbEditKhoa.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbEditKhoa.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbEditKhoa.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbEditKhoa.FillDropDown = false;
            this.cbEditKhoa.FillIndicator = false;
            this.cbEditKhoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbEditKhoa.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbEditKhoa.ForeColor = System.Drawing.Color.Black;
            this.cbEditKhoa.FormattingEnabled = true;
            this.cbEditKhoa.Icon = null;
            this.cbEditKhoa.IndicatorColor = System.Drawing.Color.SeaGreen;
            this.cbEditKhoa.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbEditKhoa.ItemBackColor = System.Drawing.Color.White;
            this.cbEditKhoa.ItemBorderColor = System.Drawing.Color.White;
            this.cbEditKhoa.ItemForeColor = System.Drawing.Color.Black;
            this.cbEditKhoa.ItemHeight = 26;
            this.cbEditKhoa.ItemHighLightColor = System.Drawing.Color.MediumSeaGreen;
            this.cbEditKhoa.Location = new System.Drawing.Point(166, 336);
            this.cbEditKhoa.Name = "cbEditKhoa";
            this.cbEditKhoa.Size = new System.Drawing.Size(238, 32);
            this.cbEditKhoa.TabIndex = 18;
            this.cbEditKhoa.Text = null;
            // 
            // txbHinhThucThi
            // 
            this.txbHinhThucThi.AcceptsReturn = false;
            this.txbHinhThucThi.AcceptsTab = false;
            this.txbHinhThucThi.AnimationSpeed = 200;
            this.txbHinhThucThi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbHinhThucThi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbHinhThucThi.BackColor = System.Drawing.Color.Transparent;
            this.txbHinhThucThi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbHinhThucThi.BackgroundImage")));
            this.txbHinhThucThi.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbHinhThucThi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbHinhThucThi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbHinhThucThi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbHinhThucThi.BorderRadius = 1;
            this.txbHinhThucThi.BorderThickness = 1;
            this.txbHinhThucThi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbHinhThucThi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbHinhThucThi.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbHinhThucThi.DefaultText = "";
            this.txbHinhThucThi.FillColor = System.Drawing.Color.White;
            this.txbHinhThucThi.HideSelection = true;
            this.txbHinhThucThi.IconLeft = null;
            this.txbHinhThucThi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbHinhThucThi.IconPadding = 10;
            this.txbHinhThucThi.IconRight = null;
            this.txbHinhThucThi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbHinhThucThi.Lines = new string[0];
            this.txbHinhThucThi.Location = new System.Drawing.Point(166, 282);
            this.txbHinhThucThi.MaxLength = 32767;
            this.txbHinhThucThi.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbHinhThucThi.Modified = false;
            this.txbHinhThucThi.Multiline = false;
            this.txbHinhThucThi.Name = "txbHinhThucThi";
            stateProperties3.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbHinhThucThi.OnActiveState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Empty;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbHinhThucThi.OnDisabledState = stateProperties4;
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbHinhThucThi.OnHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbHinhThucThi.OnIdleState = stateProperties6;
            this.txbHinhThucThi.PasswordChar = '\0';
            this.txbHinhThucThi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbHinhThucThi.PlaceholderText = "";
            this.txbHinhThucThi.ReadOnly = false;
            this.txbHinhThucThi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbHinhThucThi.SelectedText = "";
            this.txbHinhThucThi.SelectionLength = 0;
            this.txbHinhThucThi.SelectionStart = 0;
            this.txbHinhThucThi.ShortcutsEnabled = true;
            this.txbHinhThucThi.Size = new System.Drawing.Size(238, 37);
            this.txbHinhThucThi.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbHinhThucThi.TabIndex = 17;
            this.txbHinhThucThi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbHinhThucThi.TextMarginBottom = 0;
            this.txbHinhThucThi.TextMarginLeft = 5;
            this.txbHinhThucThi.TextMarginTop = 0;
            this.txbHinhThucThi.TextPlaceholder = "";
            this.txbHinhThucThi.UseSystemPasswordChar = false;
            this.txbHinhThucThi.WordWrap = true;
            // 
            // txbMaHP
            // 
            this.txbMaHP.AcceptsReturn = false;
            this.txbMaHP.AcceptsTab = false;
            this.txbMaHP.AnimationSpeed = 200;
            this.txbMaHP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbMaHP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbMaHP.BackColor = System.Drawing.Color.Transparent;
            this.txbMaHP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbMaHP.BackgroundImage")));
            this.txbMaHP.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbMaHP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbMaHP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbMaHP.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbMaHP.BorderRadius = 1;
            this.txbMaHP.BorderThickness = 1;
            this.txbMaHP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbMaHP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbMaHP.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbMaHP.DefaultText = "";
            this.txbMaHP.FillColor = System.Drawing.Color.White;
            this.txbMaHP.HideSelection = true;
            this.txbMaHP.IconLeft = null;
            this.txbMaHP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbMaHP.IconPadding = 10;
            this.txbMaHP.IconRight = null;
            this.txbMaHP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbMaHP.Lines = new string[0];
            this.txbMaHP.Location = new System.Drawing.Point(166, 77);
            this.txbMaHP.MaxLength = 32767;
            this.txbMaHP.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbMaHP.Modified = false;
            this.txbMaHP.Multiline = false;
            this.txbMaHP.Name = "txbMaHP";
            stateProperties7.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbMaHP.OnActiveState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Empty;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbMaHP.OnDisabledState = stateProperties8;
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbMaHP.OnHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbMaHP.OnIdleState = stateProperties10;
            this.txbMaHP.PasswordChar = '\0';
            this.txbMaHP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbMaHP.PlaceholderText = "";
            this.txbMaHP.ReadOnly = false;
            this.txbMaHP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbMaHP.SelectedText = "";
            this.txbMaHP.SelectionLength = 0;
            this.txbMaHP.SelectionStart = 0;
            this.txbMaHP.ShortcutsEnabled = true;
            this.txbMaHP.Size = new System.Drawing.Size(238, 37);
            this.txbMaHP.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbMaHP.TabIndex = 11;
            this.txbMaHP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbMaHP.TextMarginBottom = 0;
            this.txbMaHP.TextMarginLeft = 5;
            this.txbMaHP.TextMarginTop = 0;
            this.txbMaHP.TextPlaceholder = "";
            this.txbMaHP.UseSystemPasswordChar = false;
            this.txbMaHP.WordWrap = true;
            this.txbMaHP.TextChanged += new System.EventHandler(this.txbMaHP_TextChanged);
            // 
            // txbTenHP
            // 
            this.txbTenHP.AcceptsReturn = false;
            this.txbTenHP.AcceptsTab = false;
            this.txbTenHP.AnimationSpeed = 200;
            this.txbTenHP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbTenHP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbTenHP.BackColor = System.Drawing.Color.Transparent;
            this.txbTenHP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbTenHP.BackgroundImage")));
            this.txbTenHP.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbTenHP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbTenHP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbTenHP.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbTenHP.BorderRadius = 1;
            this.txbTenHP.BorderThickness = 1;
            this.txbTenHP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbTenHP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTenHP.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbTenHP.DefaultText = "";
            this.txbTenHP.FillColor = System.Drawing.Color.White;
            this.txbTenHP.HideSelection = true;
            this.txbTenHP.IconLeft = null;
            this.txbTenHP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTenHP.IconPadding = 10;
            this.txbTenHP.IconRight = null;
            this.txbTenHP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTenHP.Lines = new string[0];
            this.txbTenHP.Location = new System.Drawing.Point(166, 126);
            this.txbTenHP.MaxLength = 32767;
            this.txbTenHP.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbTenHP.Modified = false;
            this.txbTenHP.Multiline = false;
            this.txbTenHP.Name = "txbTenHP";
            stateProperties11.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTenHP.OnActiveState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Empty;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTenHP.OnDisabledState = stateProperties12;
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTenHP.OnHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTenHP.OnIdleState = stateProperties14;
            this.txbTenHP.PasswordChar = '\0';
            this.txbTenHP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTenHP.PlaceholderText = "";
            this.txbTenHP.ReadOnly = false;
            this.txbTenHP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbTenHP.SelectedText = "";
            this.txbTenHP.SelectionLength = 0;
            this.txbTenHP.SelectionStart = 0;
            this.txbTenHP.ShortcutsEnabled = true;
            this.txbTenHP.Size = new System.Drawing.Size(238, 37);
            this.txbTenHP.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbTenHP.TabIndex = 10;
            this.txbTenHP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbTenHP.TextMarginBottom = 0;
            this.txbTenHP.TextMarginLeft = 5;
            this.txbTenHP.TextMarginTop = 0;
            this.txbTenHP.TextPlaceholder = "";
            this.txbTenHP.UseSystemPasswordChar = false;
            this.txbTenHP.WordWrap = true;
            // 
            // btnXoa
            // 
            this.btnXoa.AllowToggling = false;
            this.btnXoa.AnimationSpeed = 200;
            this.btnXoa.AutoGenerateColors = true;
            this.btnXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnXoa.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.btnXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoa.BackgroundImage")));
            this.btnXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.ButtonText = "Xoá";
            this.btnXoa.ButtonTextMarginLeft = 15;
            this.btnXoa.ColorContrastOnClick = 45;
            this.btnXoa.ColorContrastOnHover = 45;
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnXoa.CustomizableEdges = borderEdges2;
            this.btnXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoa.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoa.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnXoa.ForeColor = System.Drawing.Color.White;
            this.btnXoa.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoa.IconMarginLeft = 11;
            this.btnXoa.IconPadding = 10;
            this.btnXoa.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXoa.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.btnXoa.IdleBorderRadius = 5;
            this.btnXoa.IdleBorderThickness = 1;
            this.btnXoa.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.btnXoa.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnXoa.IdleIconLeftImage")));
            this.btnXoa.IdleIconRightImage = null;
            this.btnXoa.IndicateFocus = false;
            this.btnXoa.Location = new System.Drawing.Point(302, 391);
            this.btnXoa.Name = "btnXoa";
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(156)))), ((int)(((byte)(154)))));
            stateProperties15.BorderRadius = 5;
            stateProperties15.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties15.BorderThickness = 1;
            stateProperties15.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(156)))), ((int)(((byte)(154)))));
            stateProperties15.ForeColor = System.Drawing.Color.White;
            stateProperties15.IconLeftImage = null;
            stateProperties15.IconRightImage = null;
            this.btnXoa.onHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(117)))), ((int)(((byte)(41)))), ((int)(((byte)(39)))));
            stateProperties16.BorderRadius = 5;
            stateProperties16.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties16.BorderThickness = 1;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(117)))), ((int)(((byte)(41)))), ((int)(((byte)(39)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.IconLeftImage = null;
            stateProperties16.IconRightImage = null;
            this.btnXoa.OnPressedState = stateProperties16;
            this.btnXoa.Size = new System.Drawing.Size(118, 45);
            this.btnXoa.TabIndex = 14;
            this.btnXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoa.TextMarginLeft = 15;
            this.btnXoa.UseDefaultRadiusAndThickness = true;
            this.btnXoa.Click += new System.EventHandler(this.btnXoa_Click);
            // 
            // txbSoTiet
            // 
            this.txbSoTiet.AcceptsReturn = false;
            this.txbSoTiet.AcceptsTab = false;
            this.txbSoTiet.AnimationSpeed = 200;
            this.txbSoTiet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSoTiet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSoTiet.BackColor = System.Drawing.Color.Transparent;
            this.txbSoTiet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSoTiet.BackgroundImage")));
            this.txbSoTiet.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbSoTiet.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbSoTiet.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbSoTiet.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbSoTiet.BorderRadius = 1;
            this.txbSoTiet.BorderThickness = 1;
            this.txbSoTiet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSoTiet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSoTiet.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbSoTiet.DefaultText = "";
            this.txbSoTiet.FillColor = System.Drawing.Color.White;
            this.txbSoTiet.HideSelection = true;
            this.txbSoTiet.IconLeft = null;
            this.txbSoTiet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSoTiet.IconPadding = 10;
            this.txbSoTiet.IconRight = null;
            this.txbSoTiet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSoTiet.Lines = new string[0];
            this.txbSoTiet.Location = new System.Drawing.Point(166, 227);
            this.txbSoTiet.MaxLength = 32767;
            this.txbSoTiet.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbSoTiet.Modified = false;
            this.txbSoTiet.Multiline = false;
            this.txbSoTiet.Name = "txbSoTiet";
            stateProperties17.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSoTiet.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSoTiet.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSoTiet.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSoTiet.OnIdleState = stateProperties20;
            this.txbSoTiet.PasswordChar = '\0';
            this.txbSoTiet.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSoTiet.PlaceholderText = "";
            this.txbSoTiet.ReadOnly = false;
            this.txbSoTiet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSoTiet.SelectedText = "";
            this.txbSoTiet.SelectionLength = 0;
            this.txbSoTiet.SelectionStart = 0;
            this.txbSoTiet.ShortcutsEnabled = true;
            this.txbSoTiet.Size = new System.Drawing.Size(238, 37);
            this.txbSoTiet.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbSoTiet.TabIndex = 11;
            this.txbSoTiet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSoTiet.TextMarginBottom = 0;
            this.txbSoTiet.TextMarginLeft = 5;
            this.txbSoTiet.TextMarginTop = 0;
            this.txbSoTiet.TextPlaceholder = "";
            this.txbSoTiet.UseSystemPasswordChar = false;
            this.txbSoTiet.WordWrap = true;
            // 
            // txbSoTinChi
            // 
            this.txbSoTinChi.AcceptsReturn = false;
            this.txbSoTinChi.AcceptsTab = false;
            this.txbSoTinChi.AnimationSpeed = 200;
            this.txbSoTinChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSoTinChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSoTinChi.BackColor = System.Drawing.Color.Transparent;
            this.txbSoTinChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSoTinChi.BackgroundImage")));
            this.txbSoTinChi.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbSoTinChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbSoTinChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbSoTinChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbSoTinChi.BorderRadius = 1;
            this.txbSoTinChi.BorderThickness = 1;
            this.txbSoTinChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSoTinChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSoTinChi.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbSoTinChi.DefaultText = "";
            this.txbSoTinChi.FillColor = System.Drawing.Color.White;
            this.txbSoTinChi.HideSelection = true;
            this.txbSoTinChi.IconLeft = null;
            this.txbSoTinChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSoTinChi.IconPadding = 10;
            this.txbSoTinChi.IconRight = null;
            this.txbSoTinChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSoTinChi.Lines = new string[0];
            this.txbSoTinChi.Location = new System.Drawing.Point(166, 171);
            this.txbSoTinChi.MaxLength = 32767;
            this.txbSoTinChi.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbSoTinChi.Modified = false;
            this.txbSoTinChi.Multiline = false;
            this.txbSoTinChi.Name = "txbSoTinChi";
            stateProperties21.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSoTinChi.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSoTinChi.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSoTinChi.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSoTinChi.OnIdleState = stateProperties24;
            this.txbSoTinChi.PasswordChar = '\0';
            this.txbSoTinChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSoTinChi.PlaceholderText = "";
            this.txbSoTinChi.ReadOnly = false;
            this.txbSoTinChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSoTinChi.SelectedText = "";
            this.txbSoTinChi.SelectionLength = 0;
            this.txbSoTinChi.SelectionStart = 0;
            this.txbSoTinChi.ShortcutsEnabled = true;
            this.txbSoTinChi.Size = new System.Drawing.Size(238, 37);
            this.txbSoTinChi.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbSoTinChi.TabIndex = 11;
            this.txbSoTinChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSoTinChi.TextMarginBottom = 0;
            this.txbSoTinChi.TextMarginLeft = 5;
            this.txbSoTinChi.TextMarginTop = 0;
            this.txbSoTinChi.TextPlaceholder = "";
            this.txbSoTinChi.UseSystemPasswordChar = false;
            this.txbSoTinChi.WordWrap = true;
            // 
            // btnSua
            // 
            this.btnSua.AllowToggling = false;
            this.btnSua.AnimationSpeed = 200;
            this.btnSua.AutoGenerateColors = true;
            this.btnSua.BackColor = System.Drawing.Color.Transparent;
            this.btnSua.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.btnSua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSua.BackgroundImage")));
            this.btnSua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSua.ButtonText = "Sửa";
            this.btnSua.ButtonTextMarginLeft = 15;
            this.btnSua.ColorContrastOnClick = 45;
            this.btnSua.ColorContrastOnHover = 45;
            this.btnSua.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSua.CustomizableEdges = borderEdges3;
            this.btnSua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSua.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSua.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnSua.ForeColor = System.Drawing.Color.White;
            this.btnSua.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSua.IconMarginLeft = 11;
            this.btnSua.IconPadding = 10;
            this.btnSua.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSua.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.btnSua.IdleBorderRadius = 5;
            this.btnSua.IdleBorderThickness = 1;
            this.btnSua.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.btnSua.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSua.IdleIconLeftImage")));
            this.btnSua.IdleIconRightImage = null;
            this.btnSua.IndicateFocus = false;
            this.btnSua.Location = new System.Drawing.Point(156, 391);
            this.btnSua.Name = "btnSua";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            stateProperties25.BorderRadius = 5;
            stateProperties25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties25.BorderThickness = 1;
            stateProperties25.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.IconLeftImage = null;
            stateProperties25.IconRightImage = null;
            this.btnSua.onHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            stateProperties26.BorderRadius = 5;
            stateProperties26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties26.BorderThickness = 1;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            stateProperties26.ForeColor = System.Drawing.Color.White;
            stateProperties26.IconLeftImage = null;
            stateProperties26.IconRightImage = null;
            this.btnSua.OnPressedState = stateProperties26;
            this.btnSua.Size = new System.Drawing.Size(118, 45);
            this.btnSua.TabIndex = 15;
            this.btnSua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSua.TextMarginLeft = 15;
            this.btnSua.UseDefaultRadiusAndThickness = true;
            this.btnSua.Click += new System.EventHandler(this.btnSua_Click);
            // 
            // btnThem
            // 
            this.btnThem.AllowToggling = false;
            this.btnThem.AnimationSpeed = 200;
            this.btnThem.AutoGenerateColors = true;
            this.btnThem.BackColor = System.Drawing.Color.Transparent;
            this.btnThem.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThem.BackgroundImage")));
            this.btnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.ButtonText = "Thêm";
            this.btnThem.ButtonTextMarginLeft = 15;
            this.btnThem.ColorContrastOnClick = 45;
            this.btnThem.ColorContrastOnHover = 45;
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnThem.CustomizableEdges = borderEdges4;
            this.btnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThem.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnThem.ForeColor = System.Drawing.Color.White;
            this.btnThem.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThem.IconMarginLeft = 11;
            this.btnThem.IconPadding = 10;
            this.btnThem.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnThem.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThem.IdleBorderRadius = 5;
            this.btnThem.IdleBorderThickness = 1;
            this.btnThem.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnThem.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnThem.IdleIconLeftImage")));
            this.btnThem.IdleIconRightImage = null;
            this.btnThem.IndicateFocus = false;
            this.btnThem.Location = new System.Drawing.Point(6, 391);
            this.btnThem.Name = "btnThem";
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties27.BorderRadius = 5;
            stateProperties27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties27.BorderThickness = 1;
            stateProperties27.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties27.ForeColor = System.Drawing.Color.White;
            stateProperties27.IconLeftImage = null;
            stateProperties27.IconRightImage = null;
            this.btnThem.onHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties28.BorderRadius = 5;
            stateProperties28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties28.BorderThickness = 1;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.IconLeftImage = null;
            stateProperties28.IconRightImage = null;
            this.btnThem.OnPressedState = stateProperties28;
            this.btnThem.Size = new System.Drawing.Size(118, 45);
            this.btnThem.TabIndex = 16;
            this.btnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThem.TextMarginLeft = 15;
            this.btnThem.UseDefaultRadiusAndThickness = true;
            this.btnThem.Click += new System.EventHandler(this.btnThem_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label1.Location = new System.Drawing.Point(21, 87);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(139, 27);
            this.label1.TabIndex = 13;
            this.label1.Text = "Mã học phần";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label6.Location = new System.Drawing.Point(21, 292);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(144, 27);
            this.label6.TabIndex = 12;
            this.label6.Text = "Hình thức thi";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label4.Location = new System.Drawing.Point(21, 237);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(76, 27);
            this.label4.TabIndex = 12;
            this.label4.Text = "Số tiết";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label3.Location = new System.Drawing.Point(21, 181);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(102, 27);
            this.label3.TabIndex = 13;
            this.label3.Text = "Số tín chỉ";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label2.Location = new System.Drawing.Point(21, 136);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(145, 27);
            this.label2.TabIndex = 12;
            this.label2.Text = "Tên học phần";
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.btnFind);
            this.groupBox2.Controls.Add(this.cbFindKhoa);
            this.groupBox2.Controls.Add(this.txbFindHP);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.label7);
            this.groupBox2.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.groupBox2.Location = new System.Drawing.Point(21, 17);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(964, 116);
            this.groupBox2.TabIndex = 19;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Tìm kiếm";
            // 
            // cbFindKhoa
            // 
            this.cbFindKhoa.BackColor = System.Drawing.Color.White;
            this.cbFindKhoa.BorderRadius = 0;
            this.cbFindKhoa.Color = System.Drawing.Color.SeaGreen;
            this.cbFindKhoa.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbFindKhoa.DisabledColor = System.Drawing.Color.Gray;
            this.cbFindKhoa.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbFindKhoa.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbFindKhoa.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbFindKhoa.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbFindKhoa.FillDropDown = false;
            this.cbFindKhoa.FillIndicator = false;
            this.cbFindKhoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbFindKhoa.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbFindKhoa.ForeColor = System.Drawing.Color.Black;
            this.cbFindKhoa.FormattingEnabled = true;
            this.cbFindKhoa.Icon = null;
            this.cbFindKhoa.IndicatorColor = System.Drawing.Color.SeaGreen;
            this.cbFindKhoa.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbFindKhoa.ItemBackColor = System.Drawing.Color.White;
            this.cbFindKhoa.ItemBorderColor = System.Drawing.Color.White;
            this.cbFindKhoa.ItemForeColor = System.Drawing.Color.Black;
            this.cbFindKhoa.ItemHeight = 26;
            this.cbFindKhoa.ItemHighLightColor = System.Drawing.Color.MediumSeaGreen;
            this.cbFindKhoa.Location = new System.Drawing.Point(553, 42);
            this.cbFindKhoa.Name = "cbFindKhoa";
            this.cbFindKhoa.Size = new System.Drawing.Size(263, 32);
            this.cbFindKhoa.TabIndex = 17;
            this.cbFindKhoa.Text = null;
            // 
            // txbFindHP
            // 
            this.txbFindHP.AcceptsReturn = false;
            this.txbFindHP.AcceptsTab = false;
            this.txbFindHP.AnimationSpeed = 200;
            this.txbFindHP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbFindHP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbFindHP.BackColor = System.Drawing.Color.Transparent;
            this.txbFindHP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbFindHP.BackgroundImage")));
            this.txbFindHP.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbFindHP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbFindHP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbFindHP.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbFindHP.BorderRadius = 1;
            this.txbFindHP.BorderThickness = 1;
            this.txbFindHP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbFindHP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbFindHP.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbFindHP.DefaultText = "";
            this.txbFindHP.FillColor = System.Drawing.Color.White;
            this.txbFindHP.HideSelection = true;
            this.txbFindHP.IconLeft = null;
            this.txbFindHP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbFindHP.IconPadding = 10;
            this.txbFindHP.IconRight = null;
            this.txbFindHP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbFindHP.Lines = new string[0];
            this.txbFindHP.Location = new System.Drawing.Point(157, 42);
            this.txbFindHP.MaxLength = 32767;
            this.txbFindHP.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbFindHP.Modified = false;
            this.txbFindHP.Multiline = false;
            this.txbFindHP.Name = "txbFindHP";
            stateProperties31.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbFindHP.OnActiveState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Empty;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbFindHP.OnDisabledState = stateProperties32;
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbFindHP.OnHoverState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Silver;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbFindHP.OnIdleState = stateProperties34;
            this.txbFindHP.PasswordChar = '\0';
            this.txbFindHP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbFindHP.PlaceholderText = "";
            this.txbFindHP.ReadOnly = false;
            this.txbFindHP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbFindHP.SelectedText = "";
            this.txbFindHP.SelectionLength = 0;
            this.txbFindHP.SelectionStart = 0;
            this.txbFindHP.ShortcutsEnabled = true;
            this.txbFindHP.Size = new System.Drawing.Size(263, 35);
            this.txbFindHP.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbFindHP.TabIndex = 11;
            this.txbFindHP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbFindHP.TextMarginBottom = 0;
            this.txbFindHP.TextMarginLeft = 5;
            this.txbFindHP.TextMarginTop = 0;
            this.txbFindHP.TextPlaceholder = "";
            this.txbFindHP.UseSystemPasswordChar = false;
            this.txbFindHP.WordWrap = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label5.Location = new System.Drawing.Point(442, 42);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(104, 27);
            this.label5.TabIndex = 12;
            this.label5.Text = "Tên Khoa";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label7.Location = new System.Drawing.Point(6, 45);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(145, 27);
            this.label7.TabIndex = 13;
            this.label7.Text = "Tên học phần";
            // 
            // btnXem
            // 
            this.btnXem.AllowToggling = false;
            this.btnXem.AnimationSpeed = 200;
            this.btnXem.AutoGenerateColors = true;
            this.btnXem.BackColor = System.Drawing.Color.Transparent;
            this.btnXem.BackColor1 = System.Drawing.Color.MediumTurquoise;
            this.btnXem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXem.BackgroundImage")));
            this.btnXem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXem.ButtonText = "Xem";
            this.btnXem.ButtonTextMarginLeft = 0;
            this.btnXem.ColorContrastOnClick = 45;
            this.btnXem.ColorContrastOnHover = 45;
            this.btnXem.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnXem.CustomizableEdges = borderEdges1;
            this.btnXem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXem.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnXem.ForeColor = System.Drawing.Color.White;
            this.btnXem.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXem.IconMarginLeft = 11;
            this.btnXem.IconPadding = 10;
            this.btnXem.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXem.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnXem.IdleBorderRadius = 5;
            this.btnXem.IdleBorderThickness = 1;
            this.btnXem.IdleFillColor = System.Drawing.Color.MediumTurquoise;
            this.btnXem.IdleIconLeftImage = null;
            this.btnXem.IdleIconRightImage = null;
            this.btnXem.IndicateFocus = false;
            this.btnXem.Location = new System.Drawing.Point(302, 15);
            this.btnXem.Name = "btnXem";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties1.BorderRadius = 5;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(229)))), ((int)(((byte)(226)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnXem.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties2.BorderRadius = 5;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(114)))), ((int)(((byte)(112)))));
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnXem.OnPressedState = stateProperties2;
            this.btnXem.Size = new System.Drawing.Size(118, 45);
            this.btnXem.TabIndex = 21;
            this.btnXem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXem.TextMarginLeft = 0;
            this.btnXem.UseDefaultRadiusAndThickness = true;
            this.btnXem.Click += new System.EventHandler(this.btnXem_Click);
            // 
            // btnFind
            // 
            this.btnFind.AllowToggling = false;
            this.btnFind.AnimationSpeed = 200;
            this.btnFind.AutoGenerateColors = true;
            this.btnFind.BackColor = System.Drawing.Color.Transparent;
            this.btnFind.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.btnFind.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFind.BackgroundImage")));
            this.btnFind.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFind.ButtonText = "Tìm kiếm";
            this.btnFind.ButtonTextMarginLeft = 0;
            this.btnFind.ColorContrastOnClick = 45;
            this.btnFind.ColorContrastOnHover = 45;
            this.btnFind.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnFind.CustomizableEdges = borderEdges5;
            this.btnFind.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFind.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFind.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFind.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFind.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFind.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnFind.ForeColor = System.Drawing.Color.White;
            this.btnFind.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnFind.IconMarginLeft = 11;
            this.btnFind.IconPadding = 10;
            this.btnFind.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnFind.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnFind.IdleBorderRadius = 5;
            this.btnFind.IdleBorderThickness = 1;
            this.btnFind.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.btnFind.IdleIconLeftImage = null;
            this.btnFind.IdleIconRightImage = null;
            this.btnFind.IndicateFocus = false;
            this.btnFind.Location = new System.Drawing.Point(829, 34);
            this.btnFind.Name = "btnFind";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties29.BorderRadius = 5;
            stateProperties29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties29.BorderThickness = 1;
            stateProperties29.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(185)))), ((int)(((byte)(185)))), ((int)(((byte)(255)))));
            stateProperties29.ForeColor = System.Drawing.Color.White;
            stateProperties29.IconLeftImage = null;
            stateProperties29.IconRightImage = null;
            this.btnFind.onHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties30.BorderRadius = 5;
            stateProperties30.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties30.BorderThickness = 1;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(140)))));
            stateProperties30.ForeColor = System.Drawing.Color.White;
            stateProperties30.IconLeftImage = null;
            stateProperties30.IconRightImage = null;
            this.btnFind.OnPressedState = stateProperties30;
            this.btnFind.Size = new System.Drawing.Size(118, 45);
            this.btnFind.TabIndex = 19;
            this.btnFind.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFind.TextMarginLeft = 0;
            this.btnFind.UseDefaultRadiusAndThickness = true;
            this.btnFind.Click += new System.EventHandler(this.btnFind_Click);
            // 
            // UC_HocPhan
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.dtgvHocPhan);
            this.Name = "UC_HocPhan";
            this.Size = new System.Drawing.Size(985, 593);
            ((System.ComponentModel.ISupportInitialize)(this.dtgvHocPhan)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dtgvHocPhan;
        private System.Windows.Forms.GroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbMaHP;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbTenHP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoa;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbSoTinChi;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThem;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.GroupBox groupBox2;
        private Bunifu.UI.WinForms.BunifuDropdown cbFindKhoa;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbSoTiet;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbFindHP;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbHinhThucThi;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuDropdown cbEditKhoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFind;
    }
}
