namespace QuanLyDiemSV.GUI.User_Control
{
    partial class UC_LopCN
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UC_LopCN));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.dtgvLopCN = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btnXem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbMaGV = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.cbEditKhoa = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txbEditMaLopCN = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txbTenLopCN = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnDeleteLopCN = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbSiSo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnUpdateLopCN = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInsertLopCN = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.cbFindKhoa = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.btnFindTenLopCN = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txbFindLopCN = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvLopCN)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label2.Location = new System.Drawing.Point(21, 138);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(69, 22);
            this.label2.TabIndex = 12;
            this.label2.Text = "Tên lớp";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label1.Location = new System.Drawing.Point(21, 80);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(65, 22);
            this.label1.TabIndex = 13;
            this.label1.Text = "Mã lớp";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label3.Location = new System.Drawing.Point(21, 190);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(46, 22);
            this.label3.TabIndex = 13;
            this.label3.Text = "Sĩ số";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label4.Location = new System.Drawing.Point(21, 238);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(52, 22);
            this.label4.TabIndex = 12;
            this.label4.Text = "Khoa";
            // 
            // dtgvLopCN
            // 
            this.dtgvLopCN.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtgvLopCN.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgvLopCN.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgvLopCN.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgvLopCN.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgvLopCN.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgvLopCN.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgvLopCN.ColumnHeadersHeight = 40;
            this.dtgvLopCN.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtgvLopCN.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvLopCN.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvLopCN.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvLopCN.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgvLopCN.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtgvLopCN.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvLopCN.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtgvLopCN.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgvLopCN.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgvLopCN.CurrentTheme.Name = null;
            this.dtgvLopCN.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgvLopCN.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvLopCN.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvLopCN.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvLopCN.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgvLopCN.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgvLopCN.EnableHeadersVisualStyles = false;
            this.dtgvLopCN.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvLopCN.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtgvLopCN.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgvLopCN.HeaderForeColor = System.Drawing.Color.White;
            this.dtgvLopCN.Location = new System.Drawing.Point(21, 148);
            this.dtgvLopCN.Name = "dtgvLopCN";
            this.dtgvLopCN.RowHeadersVisible = false;
            this.dtgvLopCN.RowHeadersWidth = 51;
            this.dtgvLopCN.RowTemplate.Height = 40;
            this.dtgvLopCN.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgvLopCN.Size = new System.Drawing.Size(504, 415);
            this.dtgvLopCN.TabIndex = 0;
            this.dtgvLopCN.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btnXem);
            this.groupBox1.Controls.Add(this.txbMaGV);
            this.groupBox1.Controls.Add(this.label7);
            this.groupBox1.Controls.Add(this.cbEditKhoa);
            this.groupBox1.Controls.Add(this.txbEditMaLopCN);
            this.groupBox1.Controls.Add(this.txbTenLopCN);
            this.groupBox1.Controls.Add(this.btnDeleteLopCN);
            this.groupBox1.Controls.Add(this.txbSiSo);
            this.groupBox1.Controls.Add(this.btnUpdateLopCN);
            this.groupBox1.Controls.Add(this.btnInsertLopCN);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.groupBox1.Location = new System.Drawing.Point(545, 136);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(437, 427);
            this.groupBox1.TabIndex = 17;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Chỉnh sửa";
            // 
            // btnXem
            // 
            this.btnXem.AllowToggling = false;
            this.btnXem.AnimationSpeed = 200;
            this.btnXem.AutoGenerateColors = true;
            this.btnXem.BackColor = System.Drawing.Color.Transparent;
            this.btnXem.BackColor1 = System.Drawing.Color.MediumTurquoise;
            this.btnXem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXem.BackgroundImage")));
            this.btnXem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXem.ButtonText = "Xem";
            this.btnXem.ButtonTextMarginLeft = 0;
            this.btnXem.ColorContrastOnClick = 45;
            this.btnXem.ColorContrastOnHover = 45;
            this.btnXem.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnXem.CustomizableEdges = borderEdges1;
            this.btnXem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXem.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnXem.ForeColor = System.Drawing.Color.White;
            this.btnXem.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXem.IconMarginLeft = 11;
            this.btnXem.IconPadding = 10;
            this.btnXem.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnXem.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnXem.IdleBorderRadius = 5;
            this.btnXem.IdleBorderThickness = 1;
            this.btnXem.IdleFillColor = System.Drawing.Color.MediumTurquoise;
            this.btnXem.IdleIconLeftImage = null;
            this.btnXem.IdleIconRightImage = null;
            this.btnXem.IndicateFocus = false;
            this.btnXem.Location = new System.Drawing.Point(304, 19);
            this.btnXem.Name = "btnXem";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties1.BorderRadius = 5;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(229)))), ((int)(((byte)(226)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnXem.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties2.BorderRadius = 5;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(114)))), ((int)(((byte)(112)))));
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnXem.OnPressedState = stateProperties2;
            this.btnXem.Size = new System.Drawing.Size(118, 45);
            this.btnXem.TabIndex = 20;
            this.btnXem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXem.TextMarginLeft = 0;
            this.btnXem.UseDefaultRadiusAndThickness = true;
            this.btnXem.Click += new System.EventHandler(this.btnXem_Click);
            // 
            // txbMaGV
            // 
            this.txbMaGV.AcceptsReturn = false;
            this.txbMaGV.AcceptsTab = false;
            this.txbMaGV.AnimationSpeed = 200;
            this.txbMaGV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbMaGV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbMaGV.BackColor = System.Drawing.Color.Transparent;
            this.txbMaGV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbMaGV.BackgroundImage")));
            this.txbMaGV.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbMaGV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbMaGV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbMaGV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbMaGV.BorderRadius = 1;
            this.txbMaGV.BorderThickness = 1;
            this.txbMaGV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbMaGV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbMaGV.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbMaGV.DefaultText = "";
            this.txbMaGV.FillColor = System.Drawing.Color.White;
            this.txbMaGV.HideSelection = true;
            this.txbMaGV.IconLeft = null;
            this.txbMaGV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbMaGV.IconPadding = 10;
            this.txbMaGV.IconRight = null;
            this.txbMaGV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbMaGV.Lines = new string[0];
            this.txbMaGV.Location = new System.Drawing.Point(120, 283);
            this.txbMaGV.MaxLength = 32767;
            this.txbMaGV.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbMaGV.Modified = false;
            this.txbMaGV.Multiline = false;
            this.txbMaGV.Name = "txbMaGV";
            stateProperties3.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbMaGV.OnActiveState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Empty;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbMaGV.OnDisabledState = stateProperties4;
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbMaGV.OnHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbMaGV.OnIdleState = stateProperties6;
            this.txbMaGV.PasswordChar = '\0';
            this.txbMaGV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbMaGV.PlaceholderText = "";
            this.txbMaGV.ReadOnly = false;
            this.txbMaGV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbMaGV.SelectedText = "";
            this.txbMaGV.SelectionLength = 0;
            this.txbMaGV.SelectionStart = 0;
            this.txbMaGV.ShortcutsEnabled = true;
            this.txbMaGV.Size = new System.Drawing.Size(263, 35);
            this.txbMaGV.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbMaGV.TabIndex = 19;
            this.txbMaGV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbMaGV.TextMarginBottom = 0;
            this.txbMaGV.TextMarginLeft = 5;
            this.txbMaGV.TextMarginTop = 0;
            this.txbMaGV.TextPlaceholder = "";
            this.txbMaGV.UseSystemPasswordChar = false;
            this.txbMaGV.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label7.Location = new System.Drawing.Point(21, 293);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(61, 22);
            this.label7.TabIndex = 18;
            this.label7.Text = "Mã GV";
            // 
            // cbEditKhoa
            // 
            this.cbEditKhoa.BackColor = System.Drawing.Color.White;
            this.cbEditKhoa.BorderRadius = 0;
            this.cbEditKhoa.Color = System.Drawing.Color.SeaGreen;
            this.cbEditKhoa.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbEditKhoa.DisabledColor = System.Drawing.Color.Gray;
            this.cbEditKhoa.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbEditKhoa.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbEditKhoa.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbEditKhoa.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbEditKhoa.FillDropDown = false;
            this.cbEditKhoa.FillIndicator = false;
            this.cbEditKhoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbEditKhoa.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbEditKhoa.ForeColor = System.Drawing.Color.Black;
            this.cbEditKhoa.FormattingEnabled = true;
            this.cbEditKhoa.Icon = null;
            this.cbEditKhoa.IndicatorColor = System.Drawing.Color.SeaGreen;
            this.cbEditKhoa.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbEditKhoa.ItemBackColor = System.Drawing.Color.White;
            this.cbEditKhoa.ItemBorderColor = System.Drawing.Color.White;
            this.cbEditKhoa.ItemForeColor = System.Drawing.Color.Black;
            this.cbEditKhoa.ItemHeight = 26;
            this.cbEditKhoa.ItemHighLightColor = System.Drawing.Color.MediumSeaGreen;
            this.cbEditKhoa.Location = new System.Drawing.Point(120, 233);
            this.cbEditKhoa.Name = "cbEditKhoa";
            this.cbEditKhoa.Size = new System.Drawing.Size(263, 32);
            this.cbEditKhoa.TabIndex = 17;
            this.cbEditKhoa.Text = null;
            // 
            // txbEditMaLopCN
            // 
            this.txbEditMaLopCN.AcceptsReturn = false;
            this.txbEditMaLopCN.AcceptsTab = false;
            this.txbEditMaLopCN.AnimationSpeed = 200;
            this.txbEditMaLopCN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbEditMaLopCN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbEditMaLopCN.BackColor = System.Drawing.Color.Transparent;
            this.txbEditMaLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbEditMaLopCN.BackgroundImage")));
            this.txbEditMaLopCN.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbEditMaLopCN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbEditMaLopCN.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbEditMaLopCN.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbEditMaLopCN.BorderRadius = 1;
            this.txbEditMaLopCN.BorderThickness = 1;
            this.txbEditMaLopCN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbEditMaLopCN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbEditMaLopCN.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbEditMaLopCN.DefaultText = "";
            this.txbEditMaLopCN.FillColor = System.Drawing.Color.White;
            this.txbEditMaLopCN.HideSelection = true;
            this.txbEditMaLopCN.IconLeft = null;
            this.txbEditMaLopCN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbEditMaLopCN.IconPadding = 10;
            this.txbEditMaLopCN.IconRight = null;
            this.txbEditMaLopCN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbEditMaLopCN.Lines = new string[0];
            this.txbEditMaLopCN.Location = new System.Drawing.Point(120, 70);
            this.txbEditMaLopCN.MaxLength = 32767;
            this.txbEditMaLopCN.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbEditMaLopCN.Modified = false;
            this.txbEditMaLopCN.Multiline = false;
            this.txbEditMaLopCN.Name = "txbEditMaLopCN";
            stateProperties7.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbEditMaLopCN.OnActiveState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Empty;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbEditMaLopCN.OnDisabledState = stateProperties8;
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbEditMaLopCN.OnHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbEditMaLopCN.OnIdleState = stateProperties10;
            this.txbEditMaLopCN.PasswordChar = '\0';
            this.txbEditMaLopCN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbEditMaLopCN.PlaceholderText = "";
            this.txbEditMaLopCN.ReadOnly = false;
            this.txbEditMaLopCN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbEditMaLopCN.SelectedText = "";
            this.txbEditMaLopCN.SelectionLength = 0;
            this.txbEditMaLopCN.SelectionStart = 0;
            this.txbEditMaLopCN.ShortcutsEnabled = true;
            this.txbEditMaLopCN.Size = new System.Drawing.Size(263, 35);
            this.txbEditMaLopCN.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbEditMaLopCN.TabIndex = 11;
            this.txbEditMaLopCN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbEditMaLopCN.TextMarginBottom = 0;
            this.txbEditMaLopCN.TextMarginLeft = 5;
            this.txbEditMaLopCN.TextMarginTop = 0;
            this.txbEditMaLopCN.TextPlaceholder = "";
            this.txbEditMaLopCN.UseSystemPasswordChar = false;
            this.txbEditMaLopCN.WordWrap = true;
            this.txbEditMaLopCN.TextChange += new System.EventHandler(this.txbEditMaLopCN_TextChange);
            // 
            // txbTenLopCN
            // 
            this.txbTenLopCN.AcceptsReturn = false;
            this.txbTenLopCN.AcceptsTab = false;
            this.txbTenLopCN.AnimationSpeed = 200;
            this.txbTenLopCN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbTenLopCN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbTenLopCN.BackColor = System.Drawing.Color.Transparent;
            this.txbTenLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbTenLopCN.BackgroundImage")));
            this.txbTenLopCN.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbTenLopCN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbTenLopCN.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbTenLopCN.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbTenLopCN.BorderRadius = 1;
            this.txbTenLopCN.BorderThickness = 1;
            this.txbTenLopCN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbTenLopCN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTenLopCN.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbTenLopCN.DefaultText = "";
            this.txbTenLopCN.FillColor = System.Drawing.Color.White;
            this.txbTenLopCN.HideSelection = true;
            this.txbTenLopCN.IconLeft = null;
            this.txbTenLopCN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTenLopCN.IconPadding = 10;
            this.txbTenLopCN.IconRight = null;
            this.txbTenLopCN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbTenLopCN.Lines = new string[0];
            this.txbTenLopCN.Location = new System.Drawing.Point(120, 128);
            this.txbTenLopCN.MaxLength = 32767;
            this.txbTenLopCN.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbTenLopCN.Modified = false;
            this.txbTenLopCN.Multiline = false;
            this.txbTenLopCN.Name = "txbTenLopCN";
            stateProperties11.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTenLopCN.OnActiveState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Empty;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTenLopCN.OnDisabledState = stateProperties12;
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTenLopCN.OnHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbTenLopCN.OnIdleState = stateProperties14;
            this.txbTenLopCN.PasswordChar = '\0';
            this.txbTenLopCN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbTenLopCN.PlaceholderText = "";
            this.txbTenLopCN.ReadOnly = false;
            this.txbTenLopCN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbTenLopCN.SelectedText = "";
            this.txbTenLopCN.SelectionLength = 0;
            this.txbTenLopCN.SelectionStart = 0;
            this.txbTenLopCN.ShortcutsEnabled = true;
            this.txbTenLopCN.Size = new System.Drawing.Size(263, 35);
            this.txbTenLopCN.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbTenLopCN.TabIndex = 10;
            this.txbTenLopCN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbTenLopCN.TextMarginBottom = 0;
            this.txbTenLopCN.TextMarginLeft = 5;
            this.txbTenLopCN.TextMarginTop = 0;
            this.txbTenLopCN.TextPlaceholder = "";
            this.txbTenLopCN.UseSystemPasswordChar = false;
            this.txbTenLopCN.WordWrap = true;
            // 
            // btnDeleteLopCN
            // 
            this.btnDeleteLopCN.AllowToggling = false;
            this.btnDeleteLopCN.AnimationSpeed = 200;
            this.btnDeleteLopCN.AutoGenerateColors = true;
            this.btnDeleteLopCN.BackColor = System.Drawing.Color.Transparent;
            this.btnDeleteLopCN.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.btnDeleteLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDeleteLopCN.BackgroundImage")));
            this.btnDeleteLopCN.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteLopCN.ButtonText = "Xoá";
            this.btnDeleteLopCN.ButtonTextMarginLeft = 15;
            this.btnDeleteLopCN.ColorContrastOnClick = 45;
            this.btnDeleteLopCN.ColorContrastOnHover = 45;
            this.btnDeleteLopCN.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnDeleteLopCN.CustomizableEdges = borderEdges2;
            this.btnDeleteLopCN.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDeleteLopCN.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnDeleteLopCN.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteLopCN.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteLopCN.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDeleteLopCN.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnDeleteLopCN.ForeColor = System.Drawing.Color.White;
            this.btnDeleteLopCN.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteLopCN.IconMarginLeft = 11;
            this.btnDeleteLopCN.IconPadding = 10;
            this.btnDeleteLopCN.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteLopCN.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.btnDeleteLopCN.IdleBorderRadius = 5;
            this.btnDeleteLopCN.IdleBorderThickness = 1;
            this.btnDeleteLopCN.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.btnDeleteLopCN.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDeleteLopCN.IdleIconLeftImage")));
            this.btnDeleteLopCN.IdleIconRightImage = null;
            this.btnDeleteLopCN.IndicateFocus = false;
            this.btnDeleteLopCN.Location = new System.Drawing.Point(304, 356);
            this.btnDeleteLopCN.Name = "btnDeleteLopCN";
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(156)))), ((int)(((byte)(154)))));
            stateProperties15.BorderRadius = 5;
            stateProperties15.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties15.BorderThickness = 1;
            stateProperties15.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(156)))), ((int)(((byte)(154)))));
            stateProperties15.ForeColor = System.Drawing.Color.White;
            stateProperties15.IconLeftImage = null;
            stateProperties15.IconRightImage = null;
            this.btnDeleteLopCN.onHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(117)))), ((int)(((byte)(41)))), ((int)(((byte)(39)))));
            stateProperties16.BorderRadius = 5;
            stateProperties16.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties16.BorderThickness = 1;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(117)))), ((int)(((byte)(41)))), ((int)(((byte)(39)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.IconLeftImage = null;
            stateProperties16.IconRightImage = null;
            this.btnDeleteLopCN.OnPressedState = stateProperties16;
            this.btnDeleteLopCN.Size = new System.Drawing.Size(118, 45);
            this.btnDeleteLopCN.TabIndex = 14;
            this.btnDeleteLopCN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDeleteLopCN.TextMarginLeft = 15;
            this.btnDeleteLopCN.UseDefaultRadiusAndThickness = true;
            this.btnDeleteLopCN.Click += new System.EventHandler(this.btnDeleteLopCN_Click);
            // 
            // txbSiSo
            // 
            this.txbSiSo.AcceptsReturn = false;
            this.txbSiSo.AcceptsTab = false;
            this.txbSiSo.AnimationSpeed = 200;
            this.txbSiSo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbSiSo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbSiSo.BackColor = System.Drawing.Color.Transparent;
            this.txbSiSo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbSiSo.BackgroundImage")));
            this.txbSiSo.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbSiSo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbSiSo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbSiSo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbSiSo.BorderRadius = 1;
            this.txbSiSo.BorderThickness = 1;
            this.txbSiSo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbSiSo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSiSo.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbSiSo.DefaultText = "";
            this.txbSiSo.FillColor = System.Drawing.Color.White;
            this.txbSiSo.HideSelection = true;
            this.txbSiSo.IconLeft = null;
            this.txbSiSo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSiSo.IconPadding = 10;
            this.txbSiSo.IconRight = null;
            this.txbSiSo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbSiSo.Lines = new string[0];
            this.txbSiSo.Location = new System.Drawing.Point(120, 180);
            this.txbSiSo.MaxLength = 32767;
            this.txbSiSo.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbSiSo.Modified = false;
            this.txbSiSo.Multiline = false;
            this.txbSiSo.Name = "txbSiSo";
            stateProperties17.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSiSo.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSiSo.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSiSo.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbSiSo.OnIdleState = stateProperties20;
            this.txbSiSo.PasswordChar = '\0';
            this.txbSiSo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbSiSo.PlaceholderText = "";
            this.txbSiSo.ReadOnly = false;
            this.txbSiSo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbSiSo.SelectedText = "";
            this.txbSiSo.SelectionLength = 0;
            this.txbSiSo.SelectionStart = 0;
            this.txbSiSo.ShortcutsEnabled = true;
            this.txbSiSo.Size = new System.Drawing.Size(263, 35);
            this.txbSiSo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbSiSo.TabIndex = 11;
            this.txbSiSo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbSiSo.TextMarginBottom = 0;
            this.txbSiSo.TextMarginLeft = 5;
            this.txbSiSo.TextMarginTop = 0;
            this.txbSiSo.TextPlaceholder = "";
            this.txbSiSo.UseSystemPasswordChar = false;
            this.txbSiSo.WordWrap = true;
            // 
            // btnUpdateLopCN
            // 
            this.btnUpdateLopCN.AllowToggling = false;
            this.btnUpdateLopCN.AnimationSpeed = 200;
            this.btnUpdateLopCN.AutoGenerateColors = true;
            this.btnUpdateLopCN.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdateLopCN.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.btnUpdateLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdateLopCN.BackgroundImage")));
            this.btnUpdateLopCN.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdateLopCN.ButtonText = "Sửa";
            this.btnUpdateLopCN.ButtonTextMarginLeft = 15;
            this.btnUpdateLopCN.ColorContrastOnClick = 45;
            this.btnUpdateLopCN.ColorContrastOnHover = 45;
            this.btnUpdateLopCN.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnUpdateLopCN.CustomizableEdges = borderEdges3;
            this.btnUpdateLopCN.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdateLopCN.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnUpdateLopCN.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdateLopCN.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdateLopCN.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpdateLopCN.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnUpdateLopCN.ForeColor = System.Drawing.Color.White;
            this.btnUpdateLopCN.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnUpdateLopCN.IconMarginLeft = 11;
            this.btnUpdateLopCN.IconPadding = 10;
            this.btnUpdateLopCN.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnUpdateLopCN.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.btnUpdateLopCN.IdleBorderRadius = 5;
            this.btnUpdateLopCN.IdleBorderThickness = 1;
            this.btnUpdateLopCN.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.btnUpdateLopCN.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUpdateLopCN.IdleIconLeftImage")));
            this.btnUpdateLopCN.IdleIconRightImage = null;
            this.btnUpdateLopCN.IndicateFocus = false;
            this.btnUpdateLopCN.Location = new System.Drawing.Point(161, 356);
            this.btnUpdateLopCN.Name = "btnUpdateLopCN";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            stateProperties21.BorderRadius = 5;
            stateProperties21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties21.BorderThickness = 1;
            stateProperties21.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.IconLeftImage = null;
            stateProperties21.IconRightImage = null;
            this.btnUpdateLopCN.onHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            stateProperties22.BorderRadius = 5;
            stateProperties22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties22.BorderThickness = 1;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            stateProperties22.ForeColor = System.Drawing.Color.White;
            stateProperties22.IconLeftImage = null;
            stateProperties22.IconRightImage = null;
            this.btnUpdateLopCN.OnPressedState = stateProperties22;
            this.btnUpdateLopCN.Size = new System.Drawing.Size(118, 45);
            this.btnUpdateLopCN.TabIndex = 15;
            this.btnUpdateLopCN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdateLopCN.TextMarginLeft = 15;
            this.btnUpdateLopCN.UseDefaultRadiusAndThickness = true;
            this.btnUpdateLopCN.Click += new System.EventHandler(this.btnUpdateLopCN_Click);
            // 
            // btnInsertLopCN
            // 
            this.btnInsertLopCN.AllowToggling = false;
            this.btnInsertLopCN.AnimationSpeed = 200;
            this.btnInsertLopCN.AutoGenerateColors = true;
            this.btnInsertLopCN.BackColor = System.Drawing.Color.Transparent;
            this.btnInsertLopCN.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnInsertLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInsertLopCN.BackgroundImage")));
            this.btnInsertLopCN.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInsertLopCN.ButtonText = "Thêm";
            this.btnInsertLopCN.ButtonTextMarginLeft = 15;
            this.btnInsertLopCN.ColorContrastOnClick = 45;
            this.btnInsertLopCN.ColorContrastOnHover = 45;
            this.btnInsertLopCN.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnInsertLopCN.CustomizableEdges = borderEdges4;
            this.btnInsertLopCN.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInsertLopCN.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInsertLopCN.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInsertLopCN.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInsertLopCN.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInsertLopCN.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnInsertLopCN.ForeColor = System.Drawing.Color.White;
            this.btnInsertLopCN.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnInsertLopCN.IconMarginLeft = 11;
            this.btnInsertLopCN.IconPadding = 10;
            this.btnInsertLopCN.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnInsertLopCN.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnInsertLopCN.IdleBorderRadius = 5;
            this.btnInsertLopCN.IdleBorderThickness = 1;
            this.btnInsertLopCN.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnInsertLopCN.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnInsertLopCN.IdleIconLeftImage")));
            this.btnInsertLopCN.IdleIconRightImage = null;
            this.btnInsertLopCN.IndicateFocus = false;
            this.btnInsertLopCN.Location = new System.Drawing.Point(6, 356);
            this.btnInsertLopCN.Name = "btnInsertLopCN";
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties23.BorderRadius = 5;
            stateProperties23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties23.BorderThickness = 1;
            stateProperties23.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties23.ForeColor = System.Drawing.Color.White;
            stateProperties23.IconLeftImage = null;
            stateProperties23.IconRightImage = null;
            this.btnInsertLopCN.onHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties24.BorderRadius = 5;
            stateProperties24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties24.BorderThickness = 1;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.IconLeftImage = null;
            stateProperties24.IconRightImage = null;
            this.btnInsertLopCN.OnPressedState = stateProperties24;
            this.btnInsertLopCN.Size = new System.Drawing.Size(118, 45);
            this.btnInsertLopCN.TabIndex = 16;
            this.btnInsertLopCN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInsertLopCN.TextMarginLeft = 15;
            this.btnInsertLopCN.UseDefaultRadiusAndThickness = true;
            this.btnInsertLopCN.Click += new System.EventHandler(this.btnInsertLopCN_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.cbFindKhoa);
            this.groupBox2.Controls.Add(this.label6);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.btnFindTenLopCN);
            this.groupBox2.Controls.Add(this.txbFindLopCN);
            this.groupBox2.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.groupBox2.Location = new System.Drawing.Point(21, 14);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(964, 116);
            this.groupBox2.TabIndex = 18;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Tìm kiếm";
            // 
            // cbFindKhoa
            // 
            this.cbFindKhoa.BackColor = System.Drawing.Color.White;
            this.cbFindKhoa.BorderRadius = 0;
            this.cbFindKhoa.Color = System.Drawing.Color.SeaGreen;
            this.cbFindKhoa.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbFindKhoa.DisabledColor = System.Drawing.Color.Gray;
            this.cbFindKhoa.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbFindKhoa.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbFindKhoa.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbFindKhoa.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbFindKhoa.FillDropDown = false;
            this.cbFindKhoa.FillIndicator = false;
            this.cbFindKhoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbFindKhoa.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbFindKhoa.ForeColor = System.Drawing.Color.Black;
            this.cbFindKhoa.FormattingEnabled = true;
            this.cbFindKhoa.Icon = null;
            this.cbFindKhoa.IndicatorColor = System.Drawing.Color.SeaGreen;
            this.cbFindKhoa.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbFindKhoa.ItemBackColor = System.Drawing.Color.White;
            this.cbFindKhoa.ItemBorderColor = System.Drawing.Color.White;
            this.cbFindKhoa.ItemForeColor = System.Drawing.Color.Black;
            this.cbFindKhoa.ItemHeight = 26;
            this.cbFindKhoa.ItemHighLightColor = System.Drawing.Color.MediumSeaGreen;
            this.cbFindKhoa.Location = new System.Drawing.Point(519, 45);
            this.cbFindKhoa.Name = "cbFindKhoa";
            this.cbFindKhoa.Size = new System.Drawing.Size(263, 32);
            this.cbFindKhoa.TabIndex = 21;
            this.cbFindKhoa.Text = null;

            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label6.Location = new System.Drawing.Point(409, 45);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(85, 22);
            this.label6.TabIndex = 20;
            this.label6.Text = "Tên Khoa";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(94)))), ((int)(((byte)(52)))));
            this.label5.Location = new System.Drawing.Point(6, 51);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(73, 22);
            this.label5.TabIndex = 19;
            this.label5.Text = "Tên Lớp";
            // 
            // btnFindTenLopCN
            // 
            this.btnFindTenLopCN.AllowToggling = false;
            this.btnFindTenLopCN.AnimationSpeed = 200;
            this.btnFindTenLopCN.AutoGenerateColors = true;
            this.btnFindTenLopCN.BackColor = System.Drawing.Color.Transparent;
            this.btnFindTenLopCN.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.btnFindTenLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFindTenLopCN.BackgroundImage")));
            this.btnFindTenLopCN.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFindTenLopCN.ButtonText = "Tìm kiếm";
            this.btnFindTenLopCN.ButtonTextMarginLeft = 0;
            this.btnFindTenLopCN.ColorContrastOnClick = 45;
            this.btnFindTenLopCN.ColorContrastOnHover = 45;
            this.btnFindTenLopCN.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnFindTenLopCN.CustomizableEdges = borderEdges5;
            this.btnFindTenLopCN.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFindTenLopCN.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFindTenLopCN.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFindTenLopCN.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFindTenLopCN.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFindTenLopCN.Font = new System.Drawing.Font("Open Sans SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnFindTenLopCN.ForeColor = System.Drawing.Color.White;
            this.btnFindTenLopCN.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnFindTenLopCN.IconMarginLeft = 11;
            this.btnFindTenLopCN.IconPadding = 10;
            this.btnFindTenLopCN.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnFindTenLopCN.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.btnFindTenLopCN.IdleBorderRadius = 5;
            this.btnFindTenLopCN.IdleBorderThickness = 1;
            this.btnFindTenLopCN.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.btnFindTenLopCN.IdleIconLeftImage = null;
            this.btnFindTenLopCN.IdleIconRightImage = null;
            this.btnFindTenLopCN.IndicateFocus = false;
            this.btnFindTenLopCN.Location = new System.Drawing.Point(828, 40);
            this.btnFindTenLopCN.Name = "btnFindTenLopCN";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            stateProperties25.BorderRadius = 5;
            stateProperties25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties25.BorderThickness = 1;
            stateProperties25.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(185)))), ((int)(((byte)(185)))), ((int)(((byte)(255)))));
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.IconLeftImage = null;
            stateProperties25.IconRightImage = null;
            this.btnFindTenLopCN.onHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            stateProperties26.BorderRadius = 5;
            stateProperties26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties26.BorderThickness = 1;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(140)))));
            stateProperties26.ForeColor = System.Drawing.Color.White;
            stateProperties26.IconLeftImage = null;
            stateProperties26.IconRightImage = null;
            this.btnFindTenLopCN.OnPressedState = stateProperties26;
            this.btnFindTenLopCN.Size = new System.Drawing.Size(118, 45);
            this.btnFindTenLopCN.TabIndex = 18;
            this.btnFindTenLopCN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFindTenLopCN.TextMarginLeft = 0;
            this.btnFindTenLopCN.UseDefaultRadiusAndThickness = true;
            this.btnFindTenLopCN.Click += new System.EventHandler(this.btnFindTenLopCN_Click);
            // 
            // txbFindLopCN
            // 
            this.txbFindLopCN.AcceptsReturn = false;
            this.txbFindLopCN.AcceptsTab = false;
            this.txbFindLopCN.AnimationSpeed = 200;
            this.txbFindLopCN.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txbFindLopCN.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txbFindLopCN.BackColor = System.Drawing.Color.Transparent;
            this.txbFindLopCN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txbFindLopCN.BackgroundImage")));
            this.txbFindLopCN.BorderColorActive = System.Drawing.Color.SeaGreen;
            this.txbFindLopCN.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txbFindLopCN.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            this.txbFindLopCN.BorderColorIdle = System.Drawing.Color.Silver;
            this.txbFindLopCN.BorderRadius = 1;
            this.txbFindLopCN.BorderThickness = 1;
            this.txbFindLopCN.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txbFindLopCN.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txbFindLopCN.DefaultFont = new System.Drawing.Font("Open Sans", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txbFindLopCN.DefaultText = "";
            this.txbFindLopCN.FillColor = System.Drawing.Color.White;
            this.txbFindLopCN.HideSelection = true;
            this.txbFindLopCN.IconLeft = null;
            this.txbFindLopCN.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbFindLopCN.IconPadding = 10;
            this.txbFindLopCN.IconRight = null;
            this.txbFindLopCN.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txbFindLopCN.Lines = new string[0];
            this.txbFindLopCN.Location = new System.Drawing.Point(104, 45);
            this.txbFindLopCN.MaxLength = 32767;
            this.txbFindLopCN.MinimumSize = new System.Drawing.Size(100, 35);
            this.txbFindLopCN.Modified = false;
            this.txbFindLopCN.Multiline = false;
            this.txbFindLopCN.Name = "txbFindLopCN";
            stateProperties27.BorderColor = System.Drawing.Color.SeaGreen;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbFindLopCN.OnActiveState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Empty;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbFindLopCN.OnDisabledState = stateProperties28;
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(85)))), ((int)(((byte)(147)))), ((int)(((byte)(119)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbFindLopCN.OnHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Silver;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txbFindLopCN.OnIdleState = stateProperties30;
            this.txbFindLopCN.PasswordChar = '\0';
            this.txbFindLopCN.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txbFindLopCN.PlaceholderText = "";
            this.txbFindLopCN.ReadOnly = false;
            this.txbFindLopCN.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txbFindLopCN.SelectedText = "";
            this.txbFindLopCN.SelectionLength = 0;
            this.txbFindLopCN.SelectionStart = 0;
            this.txbFindLopCN.ShortcutsEnabled = true;
            this.txbFindLopCN.Size = new System.Drawing.Size(263, 35);
            this.txbFindLopCN.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txbFindLopCN.TabIndex = 11;
            this.txbFindLopCN.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txbFindLopCN.TextMarginBottom = 0;
            this.txbFindLopCN.TextMarginLeft = 5;
            this.txbFindLopCN.TextMarginTop = 0;
            this.txbFindLopCN.TextPlaceholder = "";
            this.txbFindLopCN.UseSystemPasswordChar = false;
            this.txbFindLopCN.WordWrap = true;
            // 
            // UC_LopCN
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.dtgvLopCN);
            this.Name = "UC_LopCN";
            this.Size = new System.Drawing.Size(985, 593);
            ((System.ComponentModel.ISupportInitialize)(this.dtgvLopCN)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbTenLopCN;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbEditMaLopCN;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbSiSo;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuDataGridView dtgvLopCN;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInsertLopCN;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpdateLopCN;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDeleteLopCN;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.ComponentModel.BackgroundWorker backgroundWorker1;
        private System.Windows.Forms.GroupBox groupBox2;
        private Bunifu.UI.WinForms.BunifuDropdown cbEditKhoa;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbFindLopCN;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFindTenLopCN;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txbMaGV;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuDropdown cbFindKhoa;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXem;
    }
}
